import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms & Conditions — GO KALI",
  description: "GO KALI terms and conditions.",
};

const SECTIONS: { h: string; b: string }[] = [
  {
    h: "1. Acceptance of terms",
    b: "By accessing GO KALI you agree to be bound by these terms. If you disagree with any part, discontinue use. Continued use after changes constitutes acceptance.",
  },
  {
    h: "2. Educational purposes only",
    b: "GO KALI is an educational platform. All tools, lessons and the sandbox exist to teach defensive and offensive security concepts. You agree to use the information exclusively on systems you own or are explicitly authorized to test. Unauthorized access is illegal and not condoned here.",
  },
  {
    h: "3. Accounts",
    b: "You are responsible for safeguarding your credentials and for all activity under your account. Provide accurate information. We may suspend accounts used for abuse, spam or illegal activity.",
  },
  {
    h: "4. Acceptable use",
    b: "Do not attempt to extract secrets, abuse rate limits, resell access, scrape the platform at scale, or use the service to conduct attacks against third parties. The simulated sandbox must not be used to circumvent legal access controls.",
  },
  {
    h: "5. AI assistant",
    b: "Responses are generated by third-party AI models and may be inaccurate. You are responsible for verifying output before acting on it. Your API key is used only to route requests to your chosen provider.",
  },
  {
    h: "6. No warranty",
    b: "The service is provided as-is, without warranties of any kind, express or implied. We do not guarantee availability, accuracy, or fitness for any purpose.",
  },
  {
    h: "7. Limitation of liability",
    b: "To the maximum extent permitted by law, GO KALI shall not be liable for any indirect, incidental, or consequential damages arising from your use of the platform or its content.",
  },
  {
    h: "8. Changes",
    b: "We may update these terms at any time. Material changes will be announced on the site. Continued use after changes means you accept the updated terms.",
  },
];

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-3xl px-4 py-16">
      <h1 className="text-3xl font-bold tracking-tight text-white sm:text-4xl">
        Terms & <span className="text-neon">Conditions</span>
      </h1>
      <p className="mt-3 text-sm text-muted">Last updated: September 2026</p>

      <div className="mt-8 space-y-6">
        {SECTIONS.map((s) => (
          <section key={s.h}>
            <h2 className="font-semibold text-white">{s.h}</h2>
            <p className="mt-2 text-sm leading-relaxed text-muted">{s.b}</p>
          </section>
        ))}
      </div>
    </main>
  );
}